### PR TITLE
Add support for custom mypy config via pyproject.toml

### LINKED ISSUE #11: Allow overriding top-level mypy.ini settings
Multiple use cases would benefit from the ability to specify a custom top-level mypy configuration:
- enabling mypy plugins to be used together with `typing_copilot`: #6
- allowing power users to suppress individual error codes project-wide, as a measure of last resort: #4, #9
- specifying which packages mypy should type-check or ignore, to support the mypy changes introduced in 0.800: #10

This configuration could reside in a `tool.typing_copilot` section of the `pyproject.toml` file.

### PR DESCRIPTION
**Pull request by obi1kenobi**
Resolves #11. Published as a pre-release for testing: `0.7.0.dev2`.

Adds support for reading a project's `pyproject.toml` file to override the mypy global configuration with the contents of the `[tool-typing_copilot.mypy_global_config]` TOML table.

Still needs a few polish items:
- [x] CI set up via GitHub Actions.
- [x] Error messages when the config fails to be found or loaded. 
- [x] Documentation and examples on how to use the feature

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Here's an example of how a particular project that needed this feature could test it using the pre-release version on PyPI:
https://github.com/scikit-hep/pyhf/issues/1284#issuecomment-894515834

**Comment by poneill** [comment]
Hi, is this feature considered stable enough to release in a non-dev package?  We'd find this feature very useful :)

**Comment by obi1kenobi** [comment]
It should be part of the stable 0.7.0 release which is already on PyPI.

However, not all versions of mypy work with `typing_copilot`, and I've essentially given up on trying to make that be the case: I don't use this package myself, keeping up with all the unexpected behaviors of mypy is tedious and unrewarding, and I don't get paid to do it. More info here: #19

**Comment by poneill** [comment]
Understood, thanks for all of your work on it over the years.

**Pull request merged**
